Repository iadvize/dataway, pull requests merged in 2019-10, with the labels that each got.

#24 Add getEq
  src/main.ts
  test/remotedata.test.ts
Labels: enhancement

#27 fix broken doc link
  README.md
Labels: documentation

#33 misc: update react-examples with dataway 3.0.0
  examples/package.json
  examples/src/basic.js
  examples/src/codependantdata.js
  examples/src/nesteddata.js
  examples/src/simpletransform.js
  examples/yarn.lock
  package.json
Labels: documentation

#34 Add repository in packagefile
  package.json
Labels: documentation

#35 No-TICKET: fold hotfix following history rewrite mixup
  src/main.ts
  test/remotedata.test.ts
Labels: bug
